name: pipelines_templates_steps_template_sdk_setup_step
inputs:
  scriptPath:
    required: false
    type: string
  setupType:
    required: false
    default: promptflow_new_extra
    type: string
runs:
  using: composite
  steps:
  - name: Clean up installed packages
    working-directory: ${{ inputs.scriptPath }}
    continue-on-error: true
    shell: bash -el {0}
    run: |-
      conda activate release-env
      pip uninstall -y promptflow promptflow-sdk promptflow-tools
  - name: 'Build and install: promptflow with extra'
    if: inputs.setupType == 'promptflow_new_extra'
    shell: bash -el {0}
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      echo "########### pip list (Before) ###########"
      pip list
      python ./setup.py bdist_wheel
      pip install './dist/promptflow-0.0.1-py3-none-any.whl[azure]'
      echo "########### pip freeze (After) ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
  - name: 'Build and install: promptflow_open_source'
    if: inputs.setupType == 'promptflow_open_source'
    shell: bash -el {0}
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      echo "########### pip list (Before) ###########"
      pip list
      python ./setup.py bdist_wheel
      pip install './dist/promptflow-0.0.1-py3-none-any.whl[azure]'
      echo "########### pip freeze (After) ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
  - name: 'Build and install: promptflow-sdk'
    if: inputs.setupType == 'promptflow_dev'
    shell: bash -el {0}
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      python ./setup.py bdist_wheel
      pip install ./dist/promptflow_sdk-0.0.1-py3-none-any.whl
      echo "########### pip freeze ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
  - name: 'Build and install: promptflow-sdk with extra deps'
    if: inputs.setupType == 'promptflow_dev_extra'
    shell: bash -el {0}
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      python ./setup.py bdist_wheel
      pip install './dist/promptflow_sdk-0.0.1-py3-none-any.whl[azure]'
      echo "########### pip freeze ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
  - name: 'Build and install: promptflow-tools'
    shell: bash -el {0}
    run: |-
      conda activate release-env
      pip uninstall promptflow-tools
      python ./setup.py bdist_wheel
      cd dist
      package=$(ls | grep '.whl')
      eval "pip install '$package'"
      echo "########### pip freeze (After) ###########"
      pip freeze
    working-directory: src/promptflow-tools