# Pipeline link: https://dev.azure.com/msdata/Vienna/_build?definitionId=26179&_a=summary
parameters:
  - name: policyCulture
    displayName: "Policy Culture"
    type: string
    # The culture used to run policy check scan, can be region codes separated by comma, e.g. 'en-US,de-DE'
    default: 'en-US'

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.r) # Configure run or build numbers

variables:
  - name: sourceLocation
    value: $(System.DefaultWorkingDirectory)

trigger:
  - main
  - releases/*

pool:
  name: promptflow-1ES-win

steps:
- checkout: self

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      Remove-Item -Recurse -Force $(sourceLocation)/benchmark/promptflow-serve/result-archive
  displayName: 'Delete benchmark HTML files'

# https://eng.ms/docs/microsoft-security/cloud-ecosystem-security/azure-security/cloudai-security-fundamentals-engineering/security-integration/guardian-wiki/sdl-azdo-extension/PoliCheck-build-task
- task: PoliCheck@2
  inputs:
    targetType: 'F'
    targetArgument: '$(sourceLocation)'
    optionsPE: '1'
    optionsUEPATH: '$(sourceLocation)\scripts\compliance-check\user_exclusion.xml'
    result: '$(sourceLocation)\scripts\compliance-check\result.tsv'
    optionsXCLASS: 'Geopolitical'

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      if (-Not (Test-Path "$(sourceLocation)/scripts/compliance-check/result.tsv")) {
        Write-Host "PoliCheck@2 (previous step) is not supported for forked GitHub repository, which will break the following step."
        Write-Host "So as a workaround, this step will create an empty result.tsv file."
        New-Item -ItemType Directory -Force -Path "$(sourceLocation)/scripts/compliance-check"
        Set-Location "$(sourceLocation)/scripts/compliance-check"
        New-Item -ItemType File -Name "result.tsv"
      }
  displayName: 'Workaround for fork repository'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(sourceLocation)\scripts\compliance-check\Check-PolicheckScan.ps1'
    arguments: >
      -policheckResult $(sourceLocation)\scripts\compliance-check\result.tsv
  displayName: 'Check result'

- task: PublishPipelineArtifact@1
  condition: failed()
  inputs:
    targetPath: '$(sourceLocation)\scripts\compliance-check\result.tsv'
    artifactName: 'compliance-check-result'
    publishLocation: 'pipeline'

- task: CredScan@3
  displayName: 'CredScan'
  inputs:
    scanFolder: '$(sourceLocation)'

# according to doc: https://github.com/microsoft/component-detection/blob/main/docs/feature-overview.md
# CG does not support pyproject.toml, and will scan all requirements.txt
# so we need this step to:
#   1) create some requirements.txt from pyproject.toml
#   2) remove unexpected requirements.txt
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      pip install toml-to-requirements
      Write-Host "Generating requirements.txt from pyproject.toml..."
      Write-Host "##########################################"
      Write-Host "- promptflow-tracing:"
      Set-Location "$(sourceLocation)/src/promptflow-tracing/"
      toml-to-req --toml-file pyproject.toml --poetry
      Get-Content requirements.txt
      Write-Host "##########################################"
      Write-Host "- promptflow-core:"
      Set-Location "$(sourceLocation)/src/promptflow-core/"
      toml-to-req --toml-file pyproject.toml --poetry
      Get-Content requirements.txt
      Write-Host "##########################################"
      Write-Host "- promptflow-devkit:"
      Set-Location "$(sourceLocation)/src/promptflow-devkit/"
      toml-to-req --toml-file pyproject.toml --poetry
      Get-Content requirements.txt
      Write-Host "##########################################"
      Write-Host "- promptflow-azure:"
      Set-Location "$(sourceLocation)/src/promptflow-azure/"
      toml-to-req --toml-file pyproject.toml --poetry
      Get-Content requirements.txt
      Write-Host "##########################################"

      Write-Host "Removing requirements.txt..."
      Set-Location "$(sourceLocation)/"
      Write-Host "- src/promptflow/tests/*:"
      Get-ChildItem -Path "src/promptflow/tests" -Recurse -Include requirements.txt | ForEach-Object { Remove-Item -Path $_.FullName -Force }
  displayName: 'Preprocess before CG'

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  inputs:
    sourceScanPath: '$(sourceLocation)\src'
  displayName: 'Component Detection'
