name: step_sdk_setup_win
inputs:
  scriptPath:
    required: false
    type: string
  setupType:
    required: false
    default: promptflow_with_extra
    type: string
runs:
  using: composite
  steps:
  - name: Clean up installed packages
    working-directory: ${{ inputs.scriptPath }}
    continue-on-error: true
    shell: pwsh
    run: |-
      conda activate release-env
      pip uninstall -y promptflow promptflow-sdk promptflow-tools
  - name: 'Build and install: promptflow-tools'
    shell: pwsh
    run: |-
      conda activate release-env
      python ./setup.py bdist_wheel
      $package = ls dist | ? { $_.Name.Contains('.whl')}
      pip install $package.FullName
      echo "########### pip freeze (After) ###########"
      pip freeze
    working-directory: src/promptflow-tools
  - name: 'Build and install: promptflow with extra'
    if: inputs.setupType == 'promptflow_with_extra'
    shell: pwsh
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      echo "########### pip list (Before) ###########"
      pip list
      python ./setup.py bdist_wheel
      $package = ls dist | ? { $_.Name.Contains('.whl')}
      pip install $($package.FullName + "[azure]")
      echo "########### pip freeze (After) ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
  - name: 'Build and install: promptflow-sdk'
    if: inputs.setupType == 'promptflow_dev'
    shell: pwsh
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      python ./setup.py bdist_wheel
      $package = ls dist | ? { $_.Name.Contains('.whl')}
      pip install $package.FullName
      echo "########### pip freeze ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
  - name: 'Build and install: promptflow-sdk with extra deps'
    if: inputs.setupType == 'promptflow_dev_extra'
    shell: pwsh
    run: |-
      conda activate release-env
      pip install -r ./dev_requirements.txt
      python ./setup.py bdist_wheel
      $package = ls dist | ? { $_.Name.Contains('.whl')}
      pip install $($package.FullName + "[azure]")
      echo "########### pip freeze ###########"
      pip freeze
    working-directory: ${{ inputs.scriptPath }}
