#!/usr/bin/env python

import sys
import os

dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'src')

if os.environ.get('PYTHONPATH') is None:
    os.environ['PYTHONPATH'] = dir
else:
    os.environ['PYTHONPATH'] = os.pathsep.join([
        dir,
        os.environ.get('PYTHONPATH'),
    ])

if os.environ.get('PF_INSTALLER') is None:
    os.environ['PF_INSTALLER'] = 'PIP'

os.execl(sys.executable, sys.executable, '-m', 'promptflow._cli._pf.entry', *sys.argv[1:])
