# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# coding: utf-8

import os
import re
from io import open
from typing import Any, Match, cast

from setuptools import find_packages, setup

PACKAGE_NAME = "promptflow-sdk"
PACKAGE_FOLDER_PATH = "promptflow"

# Version extraction inspired from 'requests'
with open(os.path.join(PACKAGE_FOLDER_PATH, "_version.py"), "r") as fd:
    version = cast(Match[Any], re.search(r'^VERSION\s*=\s*[\'"]([^\'"]*)[\'"]', fd.read(), re.MULTILINE)).group(1)
if not version:
    raise RuntimeError("Cannot find version information")

REQUIRES = [
    "openai==0.27.8",
    # runtime requirements
    "flask==2.2.3",
    "omegaconf>=2.3.0",
    "dataset==1.6.0",
    "banal==1.0.6",
    "alembic==1.10.4",
    "sqlalchemy==1.4.48",
    "pandas==1.5.3",
    "pyarrow==9.0.0",
    "requests==2.31.0",  # vulnerability: https://github.com/advisories/GHSA-j8r2-6x86-q33q
    "python-dotenv==1.0.0",  # control plane sdk requirements, to load .env file
    # note that this package has a dependency of azure-core
    "opencensus-ext-azure==1.1.9",  # Python SDK to send telemetry to Azure Monitor.
    "keyring==24.2.0",  # control plane sdk requirements, to access system keyring service
    "pydash<6.0.0",  # control plane sdk requirements, to support parameter overrides in schema.
    "cryptography==41.0.0",  # vulnerability: https://github.com/advisories/GHSA-5cpq-8wj7-hf2v
    "colorama==0.4.6",  # producing colored terminal text for testing chat flow
    "tabulate==0.9.0",  # control plane sdk requirements, to print table in console
    "filelock>=3.4.0",  # control plane sdk requirements, to lock for multiprocessing
    "langchain==0.0.149",
    # We need to pin the version due to the issue: https://github.com/hwchase17/langchain/issues/5113
    "typing_extensions==4.5.0",
    "beautifulsoup4==4.12.2",
    "tiktoken==0.3.3",
    "msal[broker]==1.22.0",  # compatible with cryptography==41.0.0
]

setup(
    name=PACKAGE_NAME,
    version=version,
    description="PromptFlow SDK",
    author="Microsoft Corporation",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: Other/Proprietary License",
        "Operating System :: OS Independent",
    ],
    python_requires="<4.0,>=3.8",
    install_requires=REQUIRES,
    extras_require={
        "azure": [
            "azure-core==1.26.4",
            "azure-common==1.1.28",
            "azure-data-tables==12.4.2",
            "azure-storage-blob==12.13.0",
            "azure-identity==1.12.0",
            "azure-ai-ml==1.7.0",
            "azureml-ai-monitoring==0.1.0b3",
            "mlflow==2.3.2",
            "azureml-mlflow==1.50.0",
            "azure-search-documents==11.3.0",
            "azureml-core==1.52.0",  # requirement of PRS, compatible with cryptography==41.0.0
            "mltable==1.4.1",  # requirement of PRS, compatible with cryptography==41.0.0
            "pyjwt==2.4.0",  # requirement of control plane SDK
        ],
        "builtins": [],  # this is just for backward compatibility, do not add dependency here
    },
    packages=find_packages(),
    entry_points={
        "console_scripts": [
            "prt = promptflow.runtime._cli.prt:main",
            "pf = promptflow._cli.pf:main",
            "pfazure = promptflow._cli.pf_azure.pf_azure:main",
        ],
    },
    include_package_data=True,
)
