#!/bin/bash

exit_code="$1" # The exit code from nginx
signal="$2"    # The signal which caused nginx to exit (or 0)

# stop all uvicorn processes????? how????
echo "$(date -uIns) - Stopping all uvicorn processes"
pkill uvicorn
while pgrep uvicorn >/dev/null; do
  echo "$(date -uIns) - Uvicorn process is still running, waiting for 1s"
  sleep 1
done

echo "$(date -uIns) - Stopped all uvicorn processes"

killall runsvdir
