name: step_publish_test_results
inputs:
  osVersion:
    required: false
    default: "ubuntu-latest"
    type: string
  pythonVersion:
    required: false
    default: "3.9"
    type: string
  coverageThreshold:
    required: false
    default: "0.3"
    type: string
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: composite
  steps:
  - name: Download Artifacts
    uses: actions/download-artifact@v3
    with:
      path: artifacts
  - name: Display and Set Environment Variables
    run: env | sort >> $GITHUB_OUTPUT
    shell: bash -el {0}
    id: display_env
  - name: Publish Test Results
    uses: EnricoMi/publish-unit-test-result-action@v2
    with:
      check_name: "Executor Unit Test Result [${{ steps.display_env.outputs.GITHUB_HEAD_REF }}](https://github.com/microsoft/promptflow/actions/workflows/promptflow-executor-unit-test.yml?query=branch:${{ steps.display_env.outputs.GITHUB_HEAD_REF }}++)"
      comment_title: "Executor Unit Test Result [${{ steps.display_env.outputs.GITHUB_HEAD_REF }}](https://github.com/microsoft/promptflow/actions/workflows/promptflow-executor-unit-test.yml?query=branch:${{ steps.display_env.outputs.GITHUB_HEAD_REF }}++)"
      files: "artifacts/**/test-*.xml"
  - name: Generate Coverage Report
    if: ${{ inputs.coverageThreshold != 0 }}
    uses: orgoro/coverage@v3.1
    with:
      coverageFile: "artifacts/Test Results (Python ${{ inputs.pythonVersion }}) (OS ${{ inputs.osVersion }})/coverage.xml"
      token: ${{ inputs.token }}
      thresholdAll: ${{ inputs.coverageThreshold }}
