name: step_publish_test_results
inputs:
  testActionFileName:
    required: required
    type: string
  testResultTitle:
    required: false
    default: "Test Result"
    type: string
  osVersion:
    required: false
    default: "ubuntu-latest"
    type: string
  pythonVersion:
    required: false
    default: "3.9"
    type: string
  coverageThreshold:
    required: false
    default: "0.3"
    type: string
  token:
    description: 'A Github PAT'
    required: true
  context:
    description: 'The context of the status'
    required: false
    default: 'test/sdk_cli'
runs:
  using: composite
  steps:
  - name: Download Artifacts
    uses: actions/download-artifact@v3
    with:
      path: artifacts
  - name: Display and Set Environment Variables
    run: env | sort >> $GITHUB_OUTPUT
    shell: bash -el {0}
    id: display_env
  - name: Publish Test Results
    uses: EnricoMi/publish-unit-test-result-action@v2
    with:
      check_name: "${{ inputs.testResultTitle }} [${{ steps.display_env.outputs.GITHUB_HEAD_REF }}](https://github.com/microsoft/promptflow/actions/workflows/${{ inputs.testActionFileName }}?query=branch:${{ steps.display_env.outputs.GITHUB_HEAD_REF }}++)"
      comment_title: "${{ inputs.testResultTitle }} [${{ steps.display_env.outputs.GITHUB_HEAD_REF }}](https://github.com/microsoft/promptflow/actions/workflows/${{ inputs.testActionFileName }}?query=branch:${{ steps.display_env.outputs.GITHUB_HEAD_REF }}++)"
      files: "artifacts/**/test-*.xml"
  - name: Generate Coverage Report
    if: ${{ inputs.coverageThreshold != 0 }}
    uses: orgoro/coverage@v3.1
    with:
      coverageFile: "artifacts/Test Results (Python ${{ inputs.pythonVersion }}) (OS ${{ inputs.osVersion }})/coverage.xml"
      token: ${{ inputs.token }}
      thresholdAll: ${{ inputs.coverageThreshold }}
  - name: Sending Status
    run: |-
      gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ github.repository }}/statuses/${{ github.sha }} \
        -f state='success' \
        -f target_url='https://github.com/microsoft/promptflow/actions/runs/${{ github.run_id }}' \
        -f description='The build succeeded!' \
        -f context='${{ inputs.context }}'
    shell: bash -el {0}
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
