name: Flake8 Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: setup python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.9

      - name: install dependencies
        run: pip install flake8

      - name: run flake8
        run: flake8
