name: Pylint

on:
  pull_request:
    paths:
      - src/promptflow-evals/**

jobs:
  run_pylint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: setup python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: 3.9

      - uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
      - name: install pylint and azure-pylint-guidelines-checker
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          set -xe
          poetry install -C src/promptflow-evals --with dev
          poetry show -C src/promptflow-evals
      - name: run pylint
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cd src/promptflow-evals
          poetry run pylint promptflow/evals --rcfile=../../pylintrc